apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsmvn-deployment
  labels:
    app: jenkinsmvn-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkinsmvn-container
  template:
    metadata:
      labels:
        app: jenkinsmvn-container
    spec:
      containers:
        - name: jenkinsmvn-container
          image: saiteja562/mvnjavasonar:green-{{BUILD_NUMBER}}
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsmvn-service
spec:
  type: LoadBalancer
  selector:
    app: jenkinsmvn-container
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8081
